// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monoplayer.windows {
    
    
    public partial class MainWindow {
        
        private Gtk.VBox vbox1;
        
        private Gtk.VBox menus_box;
        
        private Gtk.VBox centro;
        
        private Gtk.Table table1;
        
        private Gtk.HSeparator hseparator2;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Frame frame3;
        
        private Gtk.Label label1;
        
        private Gtk.Frame frame4;
        
        private Gtk.HBox hbox2;
        
        private Gtk.ProgressBar progress;
        
        private Gtk.Label time;
        
        private Gtk.Frame frame5;
        
        private Gtk.Label label3;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Monoplayer.windows.MainWindow
            Gtk.UIManager w1 = new Gtk.UIManager();
            Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
            w1.InsertActionGroup(w2, 0);
            this.AddAccelGroup(w1.AccelGroup);
            this.Name = "Monoplayer.windows.MainWindow";
            this.Title = Mono.Unix.Catalog.GetString("Monoplayer");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child Monoplayer.windows.MainWindow.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.menus_box = new Gtk.VBox();
            this.menus_box.Name = "menus_box";
            this.menus_box.Spacing = 6;
            this.vbox1.Add(this.menus_box);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.menus_box]));
            w3.Position = 0;
            // Container child vbox1.Gtk.Box+BoxChild
            this.centro = new Gtk.VBox();
            this.centro.Name = "centro";
            this.centro.Spacing = 6;
            this.vbox1.Add(this.centro);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.centro]));
            w4.Position = 1;
            w4.Padding = ((uint)(5));
            // Container child vbox1.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(1)), ((uint)(4)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.hseparator2 = new Gtk.HSeparator();
            this.hseparator2.Name = "hseparator2";
            this.table1.Add(this.hseparator2);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.hseparator2]));
            w5.RightAttach = ((uint)(4));
            w5.XOptions = ((Gtk.AttachOptions)(7));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox1.Add(this.table1);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox1[this.table1]));
            w6.Position = 2;
            w6.Expand = false;
            w6.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            this.hbox1.BorderWidth = ((uint)(2));
            // Container child hbox1.Gtk.Box+BoxChild
            this.frame3 = new Gtk.Frame();
            this.frame3.Name = "frame3";
            this.frame3.ShadowType = ((Gtk.ShadowType)(1));
            // Container child frame3.Gtk.Container+ContainerChild
            this.label1 = new Gtk.Label();
            this.label1.WidthRequest = 150;
            this.label1.Name = "label1";
            this.label1.LabelProp = "";
            this.frame3.Add(this.label1);
            this.hbox1.Add(this.frame3);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox1[this.frame3]));
            w8.Position = 0;
            w8.Expand = false;
            w8.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.frame4 = new Gtk.Frame();
            this.frame4.Name = "frame4";
            this.frame4.ShadowType = ((Gtk.ShadowType)(1));
            // Container child frame4.Gtk.Container+ContainerChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.progress = new Gtk.ProgressBar();
            this.progress.Name = "progress";
            this.hbox2.Add(this.progress);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.hbox2[this.progress]));
            w9.Position = 0;
            // Container child hbox2.Gtk.Box+BoxChild
            this.time = new Gtk.Label();
            this.time.WidthRequest = 100;
            this.time.Name = "time";
            this.time.LabelProp = Mono.Unix.Catalog.GetString("00:00 / 00:00");
            this.hbox2.Add(this.time);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.hbox2[this.time]));
            w10.Position = 1;
            w10.Expand = false;
            w10.Fill = false;
            this.frame4.Add(this.hbox2);
            this.hbox1.Add(this.frame4);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.hbox1[this.frame4]));
            w12.Position = 1;
            // Container child hbox1.Gtk.Box+BoxChild
            this.frame5 = new Gtk.Frame();
            this.frame5.Name = "frame5";
            this.frame5.ShadowType = ((Gtk.ShadowType)(1));
            // Container child frame5.Gtk.Container+ContainerChild
            this.label3 = new Gtk.Label();
            this.label3.WidthRequest = 150;
            this.label3.Name = "label3";
            this.label3.LabelProp = "";
            this.frame5.Add(this.label3);
            this.hbox1.Add(this.frame5);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.hbox1[this.frame5]));
            w14.Position = 2;
            w14.Expand = false;
            w14.Fill = false;
            this.vbox1.Add(this.hbox1);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
            w15.Position = 3;
            w15.Expand = false;
            w15.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 628;
            this.DefaultHeight = 219;
            this.Show();
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        }
    }
}
