// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monoplayer.windows.dialogs {
    
    
    public partial class Preferences {
        
        private Gtk.Notebook notebook1;
        
        private Gtk.VBox vbox1;
        
        private Gtk.Frame frame1;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.Table table1;
        
        private Gtk.Button btn_scan;
        
        private Gtk.Entry filepath;
        
        private Gtk.Label label2;
        
        private Gtk.Label label3;
        
        private Gtk.Button select_dir;
        
        private Gtk.Label GtkLabel1;
        
        private Gtk.Label label1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Monoplayer.windows.dialogs.Preferences
            this.Name = "Monoplayer.windows.dialogs.Preferences";
            this.Title = Mono.Unix.Catalog.GetString("Preferences");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child Monoplayer.windows.dialogs.Preferences.Gtk.Container+ContainerChild
            this.notebook1 = new Gtk.Notebook();
            this.notebook1.CanFocus = true;
            this.notebook1.Name = "notebook1";
            this.notebook1.CurrentPage = 0;
            // Container child notebook1.Gtk.Notebook+NotebookChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.frame1 = new Gtk.Frame();
            this.frame1.Name = "frame1";
            this.frame1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child frame1.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(12));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.table1 = new Gtk.Table(((uint)(3)), ((uint)(4)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.btn_scan = new Gtk.Button();
            this.btn_scan.CanFocus = true;
            this.btn_scan.Name = "btn_scan";
            this.btn_scan.UseUnderline = true;
            // Container child btn_scan.Gtk.Container+ContainerChild
            Gtk.Alignment w1 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w2 = new Gtk.HBox();
            w2.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w3 = new Gtk.Image();
            w3.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-find", Gtk.IconSize.Menu, 16);
            w2.Add(w3);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w5 = new Gtk.Label();
            w5.LabelProp = Mono.Unix.Catalog.GetString("_Update Database");
            w5.UseUnderline = true;
            w2.Add(w5);
            w1.Add(w2);
            this.btn_scan.Add(w1);
            this.table1.Add(this.btn_scan);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table1[this.btn_scan]));
            w9.TopAttach = ((uint)(1));
            w9.BottomAttach = ((uint)(2));
            w9.LeftAttach = ((uint)(3));
            w9.RightAttach = ((uint)(4));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.filepath = new Gtk.Entry();
            this.filepath.CanFocus = true;
            this.filepath.Name = "filepath";
            this.filepath.IsEditable = true;
            this.filepath.InvisibleChar = '●';
            this.table1.Add(this.filepath);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table1[this.filepath]));
            w10.TopAttach = ((uint)(1));
            w10.BottomAttach = ((uint)(2));
            w10.LeftAttach = ((uint)(1));
            w10.RightAttach = ((uint)(2));
            w10.XOptions = ((Gtk.AttachOptions)(4));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("The library contains all your media files.");
            this.label2.UseMarkup = true;
            this.table1.Add(this.label2);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table1[this.label2]));
            w11.RightAttach = ((uint)(4));
            w11.XOptions = ((Gtk.AttachOptions)(4));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Path:");
            this.table1.Add(this.label3);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table1[this.label3]));
            w12.TopAttach = ((uint)(1));
            w12.BottomAttach = ((uint)(2));
            w12.XOptions = ((Gtk.AttachOptions)(4));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.select_dir = new Gtk.Button();
            this.select_dir.CanFocus = true;
            this.select_dir.Name = "select_dir";
            this.select_dir.UseUnderline = true;
            // Container child select_dir.Gtk.Container+ContainerChild
            Gtk.Alignment w13 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w14 = new Gtk.HBox();
            w14.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w15 = new Gtk.Image();
            w15.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-directory", Gtk.IconSize.Menu, 16);
            w14.Add(w15);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w17 = new Gtk.Label();
            w17.LabelProp = Mono.Unix.Catalog.GetString("Select _Directory");
            w17.UseUnderline = true;
            w14.Add(w17);
            w13.Add(w14);
            this.select_dir.Add(w13);
            this.table1.Add(this.select_dir);
            Gtk.Table.TableChild w21 = ((Gtk.Table.TableChild)(this.table1[this.select_dir]));
            w21.TopAttach = ((uint)(1));
            w21.BottomAttach = ((uint)(2));
            w21.LeftAttach = ((uint)(2));
            w21.RightAttach = ((uint)(3));
            w21.XOptions = ((Gtk.AttachOptions)(4));
            w21.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment.Add(this.table1);
            this.frame1.Add(this.GtkAlignment);
            this.GtkLabel1 = new Gtk.Label();
            this.GtkLabel1.Name = "GtkLabel1";
            this.GtkLabel1.LabelProp = Mono.Unix.Catalog.GetString("<b>Library</b>");
            this.GtkLabel1.UseMarkup = true;
            this.frame1.LabelWidget = this.GtkLabel1;
            this.vbox1.Add(this.frame1);
            Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.vbox1[this.frame1]));
            w24.Position = 0;
            this.notebook1.Add(this.vbox1);
            // Notebook tab
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Media");
            this.label1.UseMarkup = true;
            this.notebook1.SetTabLabel(this.vbox1, this.label1);
            this.label1.ShowAll();
            this.Add(this.notebook1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 448;
            this.DefaultHeight = 297;
            this.Show();
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
            this.select_dir.Clicked += new System.EventHandler(this.OnSelectDirClicked);
            this.btn_scan.Clicked += new System.EventHandler(this.OnBtnScanClicked);
        }
    }
}
