// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monoplayer.windows.player {
    
    
    public partial class buttons {
        
        private Gtk.VBox vbox3;
        
        private Gtk.HButtonBox hbuttonbox1;
        
        private Gtk.Button btn_prev;
        
        private Gtk.Button btn_play;
        
        private Gtk.Button btn_next;
        
        private Gtk.Table table2;
        
        private Gtk.EventBox eventbox;
        
        private Gtk.Image cover_image;
        
        private Gtk.Label txt_album;
        
        private Gtk.Label txt_author;
        
        private Gtk.Label txt_song;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Monoplayer.windows.player.buttons
            Stetic.BinContainer.Attach(this);
            this.Name = "Monoplayer.windows.player.buttons";
            // Container child Monoplayer.windows.player.buttons.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.hbuttonbox1 = new Gtk.HButtonBox();
            this.hbuttonbox1.Spacing = 6;
            this.hbuttonbox1.LayoutStyle = ((Gtk.ButtonBoxStyle)(3));
            // Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
            this.btn_prev = new Gtk.Button();
            this.btn_prev.CanFocus = true;
            this.btn_prev.Name = "btn_prev";
            this.btn_prev.UseStock = true;
            this.btn_prev.UseUnderline = true;
            this.btn_prev.Label = "gtk-media-previous";
            this.hbuttonbox1.Add(this.btn_prev);
            Gtk.ButtonBox.ButtonBoxChild w1 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.btn_prev]));
            w1.Expand = false;
            w1.Fill = false;
            // Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
            this.btn_play = new Gtk.Button();
            this.btn_play.CanFocus = true;
            this.btn_play.Name = "btn_play";
            this.btn_play.UseStock = true;
            this.btn_play.UseUnderline = true;
            this.btn_play.Label = "gtk-media-play";
            this.hbuttonbox1.Add(this.btn_play);
            Gtk.ButtonBox.ButtonBoxChild w2 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.btn_play]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
            this.btn_next = new Gtk.Button();
            this.btn_next.CanFocus = true;
            this.btn_next.Name = "btn_next";
            this.btn_next.UseStock = true;
            this.btn_next.UseUnderline = true;
            this.btn_next.Label = "gtk-media-next";
            this.hbuttonbox1.Add(this.btn_next);
            Gtk.ButtonBox.ButtonBoxChild w3 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.btn_next]));
            w3.Position = 2;
            w3.Expand = false;
            w3.Fill = false;
            this.vbox3.Add(this.hbuttonbox1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbuttonbox1]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.table2 = new Gtk.Table(((uint)(3)), ((uint)(2)), false);
            this.table2.Name = "table2";
            this.table2.RowSpacing = ((uint)(6));
            this.table2.ColumnSpacing = ((uint)(6));
            this.table2.BorderWidth = ((uint)(5));
            // Container child table2.Gtk.Table+TableChild
            this.eventbox = new Gtk.EventBox();
            this.eventbox.Name = "eventbox";
            // Container child eventbox.Gtk.Container+ContainerChild
            this.cover_image = new Gtk.Image();
            this.cover_image.WidthRequest = 100;
            this.cover_image.HeightRequest = 100;
            this.cover_image.Name = "cover_image";
            this.cover_image.Pixbuf = Gdk.Pixbuf.LoadFromResource("no-cover.png");
            this.eventbox.Add(this.cover_image);
            this.table2.Add(this.eventbox);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table2[this.eventbox]));
            w6.BottomAttach = ((uint)(3));
            w6.XOptions = ((Gtk.AttachOptions)(4));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.txt_album = new Gtk.Label();
            this.txt_album.Name = "txt_album";
            this.txt_album.LabelProp = "";
            this.table2.Add(this.txt_album);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table2[this.txt_album]));
            w7.TopAttach = ((uint)(2));
            w7.BottomAttach = ((uint)(3));
            w7.LeftAttach = ((uint)(1));
            w7.RightAttach = ((uint)(2));
            w7.XOptions = ((Gtk.AttachOptions)(0));
            w7.YOptions = ((Gtk.AttachOptions)(0));
            // Container child table2.Gtk.Table+TableChild
            this.txt_author = new Gtk.Label();
            this.txt_author.Name = "txt_author";
            this.txt_author.LabelProp = "";
            this.table2.Add(this.txt_author);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table2[this.txt_author]));
            w8.TopAttach = ((uint)(1));
            w8.BottomAttach = ((uint)(2));
            w8.LeftAttach = ((uint)(1));
            w8.RightAttach = ((uint)(2));
            w8.XOptions = ((Gtk.AttachOptions)(0));
            w8.YOptions = ((Gtk.AttachOptions)(0));
            // Container child table2.Gtk.Table+TableChild
            this.txt_song = new Gtk.Label();
            this.txt_song.Name = "txt_song";
            this.txt_song.LabelProp = "";
            this.txt_song.Selectable = true;
            this.table2.Add(this.txt_song);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table2[this.txt_song]));
            w9.LeftAttach = ((uint)(1));
            w9.RightAttach = ((uint)(2));
            w9.XOptions = ((Gtk.AttachOptions)(0));
            w9.YOptions = ((Gtk.AttachOptions)(0));
            this.vbox3.Add(this.table2);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox3[this.table2]));
            w10.Position = 1;
            w10.Expand = false;
            w10.Fill = false;
            this.Add(this.vbox3);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.btn_prev.Clicked += new System.EventHandler(this.OnBtnPrevClicked);
            this.btn_play.Clicked += new System.EventHandler(this.OnBtnPlayClicked);
            this.btn_next.Clicked += new System.EventHandler(this.OnBtnNextClicked);
            this.eventbox.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnEventboxButtonPressEvent);
        }
    }
}
